# for dev and test are in same account in different region

dev:
  accountid: 730335449261
  repo-name: test
  region: ap-southeast-2
  cluster_name: dev-petclinic-cluster
  service_name: petclinic
test:
  accountid: 12345768890
  ECR-repository: 
  region:
  cluster_name:
  service_name:
prod:
  accountid: 143678902
  ECR-repository: 
  region:
  cluster_name:
  service_name:
